#!/usr/bin/env node
/* THE README'S NUMBERS, COUNTED RATHER THAN TYPED
 *
 * README.md contains this sentence about itself:
 *
 *   "This file spent a fortnight claiming 6,874 elements while the corpus held
 *    7,423, which is precisely the argument for not hand-maintaining a second
 *    one."
 *
 * It then went on to hand-maintain its own status table, and by 5 Sep that
 * table read 7,576 elements against a corpus of 8,242, claimed 7,576 drawings
 * when 367 elements were on a family fallback, and asserted "numbers 0
 * unsupported" when the source audit had 37 open. It also disagreed with
 * itself about the audit — 295 of 677 in one row and 47 in another.
 *
 * So the block between the markers is generated, the way guide.html is, and
 * --check fails if it has drifted. A claim about the corpus that lives outside
 * the corpus goes stale; the only reliable fix is to stop writing it down.
 *
 *   node tools/readme.mjs           rewrite the status block
 *   node tools/readme.mjs --check   fail if it has drifted
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const D = (p) => JSON.parse(readFileSync(join(ROOT, 'data', p), 'utf8'));
const n = (x) => x.toLocaleString('en-US');

const elements = D('elements.json');
const recipes  = D('recipes.json');
const art      = D('art-pending.json');
const cautions = D('cautions.json').hazards;
const scale    = D('scale.json');
const roles    = D('roles.json').roles;
const hom      = D('homonyms.json');
const places   = D('places.json');
const pcov     = D('places-coverage.json');
const needs    = D('needs.json').needs;
const effects  = D('effects.json');

const shelf = elements.reduce((a, e) => (a[e.shelf] = (a[e.shelf] || 0) + 1, a), {});
const verbRecipes = recipes.filter(r => r.verb).length;
const madeBy = new Map();
for (const r of recipes) madeBy.set(r.out, (madeBy.get(r.out) || 0) + 1);
const sole = [...madeBy.values()].filter(v => v === 1).length;
const cautioned = new Set(Object.values(cautions).flatMap(h => h.ids || [])).size;
const es = Object.values(scale).map(v => v.e);
const verified = recipes.filter(r => r.verified).length;

const rows = [
  ['Domain', 'Dirt to Dinner, extending into chemistry, metallurgy, biology, medicine and the built world'],
  ['Elements', `**${n(elements.length)}** (${n(shelf.workshop || 0)} workshop · ${n(shelf.folklore || 0)} folklore)`],
  ['Recipes', `**${n(recipes.length)}** (${n(recipes.length - verbRecipes)} merges · ${n(verbRecipes)} verb processes)`],
  ['Starters', 'Stone · Water · Sun · Seed'],
  ['Reachable', `**${n(elements.length)} / ${n(elements.length)}** from the four starters`],
  ['Sourced', `**${n(recipes.filter(r => r.src).length)} / ${n(recipes.length)}** recipes, every URL machine-verified`],
  ['Independently verified', `**${n(verified)} / ${n(recipes.length)}** (${(verified / recipes.length * 100).toFixed(0)}%) carry \`verified: true\``],
  ['Routes per element', `**${(recipes.length / madeBy.size).toFixed(2)}** · ${n(sole)} still have exactly one`],
  ['Hazards', `**${n(Object.keys(cautions).length)}**, covering ${n(cautioned)} elements`],
  ['Scale span', `**${Math.max(...es) - Math.min(...es) + 1} orders of magnitude**, 10^${Math.min(...es)} m to 10^${Math.max(...es)} m`],
  ['Drawings', `**${n(art.hand_drawn)}** hand-drawn; ${n(art.pending.length)} on a family fallback — a tracked backlog, not a blocker`],
  ['Roles', `**${n(Object.keys(roles).length)} / ${n(elements.length)}** — what each noun is to a making`],
  ['Sense-checked', `**${n(hom.cleared.length + hom.watch.length)}** single-word names read; ${n(hom.watch.length)} on the watchlist`],
  ['Places', `**${n(pcov.satisfied)} / ${n(pcov.wanted)}** of a checklist that is part external, so it can disagree with us`],
  ['Parts lists', `**${n(Object.keys(needs).length)}** written`],
  ['Effects on a body', (() => {
    const all = Object.values(effects.effects).flat();
    const good = all.filter(f => f.valence === 'benefit').length;
    const both = Object.values(effects.effects).filter(l => new Set(l.map(f => f.valence)).size > 1).length;
    return `**${n(all.length)}** across ${n(Object.keys(effects.effects).length)} elements and ${n(Object.keys(effects.verbs).length)} verbs — ${n(good)} of them things the body is better off for, and ${n(both)} elements that are both`;
  })()],
  ['Colours', '**28**, every one a measured Munsell chip'],
];

const block = ['<!-- STATUS:BEGIN — generated by tools/readme.mjs, do not edit by hand -->',
  '| | |', '|---|---|',
  ...rows.map(([k, v]) => `| ${k} | ${v} |`),
  '', `*Counted by \`node tools/readme.mjs\`. Every figure here is read from the corpus at`,
  `build time, because this file previously spent a fortnight claiming 6,874 elements`,
  `while the corpus held 7,423 — and then did it again, claiming ${n(7576)} against ${n(elements.length)}.*`,
  '<!-- STATUS:END -->'].join('\n');

const path = join(ROOT, 'README.md');
const md = readFileSync(path, 'utf8');
const re = /<!-- STATUS:BEGIN[\s\S]*?<!-- STATUS:END -->/;
if (!re.test(md)) {
  console.error('README.md has no STATUS block. Add the two markers around the status table.');
  process.exit(1);
}
const next = md.replace(re, block);
if (process.argv[2] === '--check') {
  if (next !== md) { console.error('README.md status block is out of date — run: node tools/readme.mjs'); process.exit(1); }
  console.log('README status block is current.');
  process.exit(0);
}
writeFileSync(path, next);
console.log(`wrote README.md status block — ${n(elements.length)} elements, ${n(recipes.length)} recipes`);
